/* ── Food images — 54 unique Pexels CDN links, optimized ── */
const P = (id: number) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`

const IMG = {
  // ── Shawarma Special (11 chicken) ──
  brothersSpecial: P(18177324),
  smokyTandoori:   P(5175631),
  openChicken:     P(18330008),
  crispy:          P(29306505),
  maharaja:        P(17200358),
  doubleCheese:    P(29285458),
  garlic:          P(15913640),
  tikka:           P(33430554),
  hotSpicy:        P(14979832),
  oregano:         P(9624298),
  nagpurSpecial:   P(27054745),
  // ── Basic Choice (5 chicken) ──
  specialChicken:  P(29850814),
  regularChicken:  P(5779364),
  cheeseChicken:   P(32845316),
  periPeri:        P(18177330),
  specialCheese:   P(32845317),
  // ── Paneer Shawarma (9) ──
  paneerSpecial:      P(29173105),
  paneerTandoori:     P(20395267),
  paneerMaharaja:     'https://vps029.manageserver.in/test/wp-content/uploads/2024/04/images-7.jpeg',
  paneerTikka:        P(12737919),
  paneerDoubleCheese: P(33430558),
  paneerOpen:         P(29173093),
  paneerNagpur:       P(29631468),
  paneerButter:       P(28674560),
  paneerHotSpicy:     P(29631461),
  // ── Special Veg Shawarma (11) ──
  vegOpen:           P(9980764),
  vegTandoori:       P(34106240),
  vegTikka:          P(4899787),
  vegPeriPeri:        'https://lh3.googleusercontent.com/p/AF1QipO9SlXQO6iMhl5G7KP1D6T0bLw4FSYZZMBxRtuE=s1360-w1360-h1020-rw',
  vegCheese:         P(28442524),
  vegCheesy:         P(34216153),
  vegZerk:           P(27054747),
  vegButterDelight:  P(18177337),
  vegFries:          P(18177325),
  vegFriesPaneer:    P(33682598),
  vegMaharaja:       P(10361459),
  // ── Rumali Roti Shawarma (4) ──
  rumaliMaharaja:       P(18177341),
  rumaliBrother:        P(7564714),
  rumaliTandoori:       P(8018000),
  rumaliPaneer:         P(23025180),
  // ── Rumali Roti Paneer Shawarma (3) ──
  rumaliPaneerBrother:  P(33215435),
  rumaliPaneerSpicy:    P(17200361),
  rumaliPaneerTandoori: P(461198),
  // ── Combos (3) ──
  combo1: P(7703785),
  combo2: P(32986489),
  combo3: P(32986483),
  // ── Momos (5) ──
  chickenFriedMomos: P(28445587),
  chickenSteamMomos: P(3911228),
  paneerSteamMomos:  P(28445589),
  vegFriedMomos:     P(5409009),
  vegSteamMomos:     P(28445593),
  // ── Fries (3) ──
  periPeriFries: P(115740),
  saltedFries:   P(1583884),
  regularFries:  P(30270643),
}

export const MENU_ITEMS = [
  // ── Shawarma Basic Choice (5) ──
  { id: 1, name: 'Special Chicken Shawarma', description: 'Elevated shawarma with thicker chicken, extra veggies and a potentially saucier presentation.', price: 109, originalPrice: 139, category: 'Shawarma Basic Choice', image: IMG.specialChicken, veg: false, rating: 4.3, popular: true },
  { id: 2, name: 'Regular Chicken Shawarma', description: 'Classic version featuring marinated, thinly sliced chicken slow cooked on a rotisserie and served shaved, offering juicy tenderness and flavorful char.', price: 89, originalPrice: 109, category: 'Shawarma Basic Choice', image: IMG.regularChicken, veg: false, rating: 4.5, popular: true },
  { id: 3, name: 'Cheese Chicken Shawarma', description: 'Succulent, spiced chicken with melted cheese wrapped in warm flatbread with fresh veggies and creamy sauce.', price: 139, category: 'Shawarma Basic Choice', image: IMG.cheeseChicken, veg: false, rating: 4.6, popular: true },
  { id: 4, name: 'Peri Peri Chicken Shawarma', description: 'Classic shawarma with a fiery twist marinated in peri peri sauce for a spicy kick.', price: 139, category: 'Shawarma Basic Choice', image: IMG.periPeri, veg: false, rating: 4.8, popular: true },
  { id: 5, name: 'Special With Cheese Chicken Shawarma', description: 'A savory fusion of Middle Eastern spices and grilled chicken, topped with melted cheese, wrapped in a warm pita.', price: 159, category: 'Shawarma Basic Choice', image: IMG.specialCheese, veg: false, rating: 4.8, popular: false },

  // ── Shawarma Special (11) ──
  { id: 6, name: 'Brothers Special Chicken Shawarma', description: 'Tender, marinated chicken slow roasted on a spit and shaved off for flavorful wraps or plates.', price: 159, category: 'Shawarma Special', image: IMG.brothersSpecial, veg: false, rating: 4.5, popular: true },
  { id: 7, name: 'Smoky Tandoori Chicken Shawarma', description: 'Marinated chicken infused with tandoori spices, slow cooked on a rotisserie for a smoky and flavorful twist on the classic shawarma.', price: 159, category: 'Shawarma Special', image: IMG.smokyTandoori, veg: false, rating: 4.8, popular: true },
  { id: 8, name: 'Open Chicken Shawarma', description: 'Chicken salad served with special sauces, presented open-faced for a premium experience.', price: 190, category: 'Shawarma Special', image: IMG.openChicken, veg: false, rating: 4.7, popular: true },
  { id: 9, name: 'Crispy Chicken Shawarma', description: 'Crispy fried chicken strips rolled in pita bread with special sauce.', price: 159, category: 'Shawarma Special', image: IMG.crispy, veg: false, rating: 4.8, popular: true },
  { id: 10, name: 'Maharaja Shawarma', description: 'A royal blend of Indian spices and succulent grilled chicken, wrapped in a pita bread fit for royalty.', price: 179, category: 'Shawarma Special', image: IMG.maharaja, veg: false, rating: 4.3, popular: true },
  { id: 11, name: 'Double Cheese Chicken Shawarma', description: 'Over loaded with cheese and chicken for the ultimate indulgence.', price: 159, category: 'Shawarma Special', image: IMG.doubleCheese, veg: false, rating: 3.9, popular: false },
  { id: 12, name: 'Yummy Garlic Chicken Shawarma', description: 'Succulent chicken marinated in a garlicky yogurt sauce, slow roasted on a spit for a flavorful and aromatic shawarma experience.', price: 159, category: 'Shawarma Special', image: IMG.garlic, veg: false, rating: 4.6, popular: true },
  { id: 13, name: 'Chicken Tikka Shawarma', description: 'Spiced chicken rolled with sliced onion and special sauce.', price: 179, category: 'Shawarma Special', image: IMG.tikka, veg: false, rating: 5.0, popular: true },
  { id: 14, name: 'Hot And Spicy Chicken Shawarma', description: 'Fiery and flavorful, this shawarma features chicken marinated in a chilli infused sauce, slow cooked on a spit for a taste bud tingling treat.', price: 159, category: 'Shawarma Special', image: IMG.hotSpicy, veg: false, rating: 3.4, popular: false },
  { id: 15, name: 'Nagpur Special Chicken Shawarma', description: 'Special spiced chicken rolled in pita bread — a local favourite.', price: 169, category: 'Shawarma Special', image: IMG.nagpurSpecial, veg: false, rating: 0, popular: false },
  { id: 16, name: 'Oregano Chicken Shawarma', description: 'Tender chicken marinated with oregano and other herbs for a unique and flavorful twist on the classic Middle Eastern dish.', price: 159, category: 'Shawarma Special', image: IMG.oregano, veg: false, rating: 0, popular: false },

  // ── Paneer Shawarma (9) ──
  { id: 17, name: 'Paneer Brother Special Shawarma', description: "A taste sensation — marinated paneer, crisp veggies & creamy sauce in warm flatbread.", price: 139, category: 'Paneer Shawarma', image: IMG.paneerSpecial, veg: true, rating: 4.8, popular: true },
  { id: 18, name: 'Paneer Smokey Tandoori Shawarma', description: 'A tantalizing fusion of smoky tandoori flavors with paneer, wrapped in a warm flatbread for a delightful twist.', price: 139, category: 'Paneer Shawarma', image: IMG.paneerTandoori, veg: true, rating: 4.3, popular: false },
  { id: 19, name: 'Maharaja Paneer Shawarma', description: 'Paneer rolled in 4 variety of sauce for a royal veg experience.', price: 189, category: 'Paneer Shawarma', image: IMG.paneerMaharaja, veg: true, rating: 0, popular: false },
  { id: 20, name: 'Paneer Tikka Shawarma', description: 'Marinated paneer rolled with onion and special spice.', price: 179, category: 'Paneer Shawarma', image: IMG.paneerTikka, veg: true, rating: 0, popular: false },
  { id: 21, name: 'Double Cheese Paneer Shawarma', description: 'Over loaded with cheese and paneer for a rich, indulgent bite.', price: 169, category: 'Paneer Shawarma', image: IMG.paneerDoubleCheese, veg: true, rating: 5.0, popular: true },
  { id: 22, name: 'Open Paneer Shawarma', description: 'Marinated paneer, fresh vegetables, and tangy sauces, served open-faced for a vibrant and delicious treat.', price: 179, category: 'Paneer Shawarma', image: IMG.paneerOpen, veg: true, rating: 2.0, popular: false },
  { id: 23, name: 'Nagpur Special Paneer Shawarma', description: 'Special spiced paneer rolled in pita bread.', price: 169, category: 'Paneer Shawarma', image: IMG.paneerNagpur, veg: true, rating: 0, popular: false },
  { id: 24, name: 'Paneer Butter Delight Shawarma', description: 'Creamy, butter-infused paneer wrapped in soft bread, offering a rich and savory taste sensation.', price: 139, category: 'Paneer Shawarma', image: IMG.paneerButter, veg: true, rating: 4.2, popular: false },
  { id: 25, name: 'Paneer Hot And Spicy Shawarma', description: 'A fiery burst of flavors with succulent paneer, zesty spices, and a tantalizing kick.', price: 139, category: 'Paneer Shawarma', image: IMG.paneerHotSpicy, veg: true, rating: 4.0, popular: false },

  // ── Combos (3) ──
  { id: 26, name: 'Chicken Shawarma Combo', description: 'Chicken Shawarma [Regular] + Special Chicken Shawarma — the perfect duo.', price: 220, category: 'Combos', image: IMG.combo1, veg: false, rating: 4.6, popular: true },
  { id: 27, name: 'Special Chicken Shawarma With Open Chicken Shawarma', description: 'Chicken Shawarma [Regular] + Cheese Chicken Shawarma — a loaded treat.', price: 289, category: 'Combos', image: IMG.combo2, veg: false, rating: 4.0, popular: false },
  { id: 28, name: 'Cheese Chicken Shawarma With Open Chicken Shawarma', description: 'A savory fusion of Middle Eastern spices and grilled chicken, topped with melted cheese, wrapped in a warm pita.', price: 289, category: 'Combos', image: IMG.combo3, veg: false, rating: 0, popular: false },

  // ── Special Veg Shawarma (11) ──
  { id: 29, name: 'Open Paneer Special Shawarma', description: 'Open-face paneer shawarma with special toppings and premium sauces.', price: 189, category: 'Special Veg Shawarma', image: IMG.vegOpen, veg: true, rating: 0, popular: false },
  { id: 30, name: 'Tandoori Paneer Shawarma', description: 'Smoky tandoori paneer in a warm flatbread wrap.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegTandoori, veg: true, rating: 3.0, popular: false },
  { id: 31, name: 'Paneer Tikka Special Shawarma', description: 'Tikka-spiced paneer wrapped with fresh veggies and sauces.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegTikka, veg: true, rating: 0, popular: false },
  { id: 32, name: 'Peri Peri Paneer Shawarma', description: 'Spicy peri peri marinated paneer wrapped in soft bread.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegPeriPeri, veg: true, rating: 4.0, popular: false },
  { id: 33, name: 'Special With Cheese Paneer Shawarma', description: 'Premium paneer shawarma loaded with melted cheese.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegCheese, veg: true, rating: 0, popular: false },
  { id: 34, name: 'Cheesy Paneer Shawarma', description: 'Extra cheesy paneer wrap with fresh veggies.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegCheesy, veg: true, rating: 0, popular: false },
  { id: 35, name: 'Zerk Paneer Shawarma', description: 'Signature zerk-style paneer wrap with house special sauce.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegZerk, veg: true, rating: 0, popular: false },
  { id: 36, name: 'Paneer Butter Delight Special Shawarma', description: 'Special butter-infused paneer in a warm wrap.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegButterDelight, veg: true, rating: 0, popular: false },
  { id: 37, name: 'Fries Shawarma', description: 'Crispy fries stuffed inside a shawarma wrap.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegFries, veg: true, rating: 0, popular: false },
  { id: 38, name: 'Fries Paneer Shawarma', description: 'Paneer and crispy fries together in a delicious wrap.', price: 149, category: 'Special Veg Shawarma', image: IMG.vegFriesPaneer, veg: true, rating: 0, popular: false },
  { id: 39, name: 'Maharaja Paneer Special Shawarma', description: 'The royal paneer shawarma with 4 premium sauces.', price: 189, category: 'Special Veg Shawarma', image: IMG.vegMaharaja, veg: true, rating: 0, popular: false },

  // ── Special Rumali Roti Shawarma (4) ──
  { id: 40, name: 'Rumali Maharaja Shawarma', description: 'Tender chicken marinated in rich spices, wrapped in soft Rumali Roti for a royal and flavorful treat.', price: 199, category: 'Special Rumali Roti Shawarma', image: IMG.rumaliMaharaja, veg: false, rating: 5.0, popular: true },
  { id: 41, name: 'Rumali Brother Special Shawarma', description: 'Tender, juicy meat with a blend of aromatic spices, wrapped in soft, thin Rumali Roti for a delectable experience.', price: 169, category: 'Special Rumali Roti Shawarma', image: IMG.rumaliBrother, veg: false, rating: 4.7, popular: true },
  { id: 42, name: 'Rumali Smooky Tandoori Shawarma', description: 'Smoky, tandoori-marinated chicken with soft Rumali Roti, creating a flavorful and aromatic delight.', price: 169, category: 'Special Rumali Roti Shawarma', image: IMG.rumaliTandoori, veg: false, rating: 0, popular: false },
  { id: 43, name: 'Special Paneer Rumali Roti Shawarma', description: 'Paneer wrapped in delicate Rumali Roti with special sauces. [Veg preparation]', price: 179, category: 'Special Rumali Roti Shawarma', image: IMG.rumaliPaneer, veg: true, rating: 0, popular: false },

  // ── Momos (5) ──
  { id: 44, name: 'Chicken Fried Momos', description: '8 Piece — Crispy fried chicken momos.', price: 220, category: 'Momos', image: IMG.chickenFriedMomos, veg: false, rating: 0, popular: false },
  { id: 45, name: 'Chicken Steam Momos', description: '8 Piece — Steamed chicken dumplings.', price: 180, category: 'Momos', image: IMG.chickenSteamMomos, veg: false, rating: 3.1, popular: false },
  { id: 46, name: 'Paneer Steam Momos', description: '8 Piece — Steamed paneer dumplings.', price: 160, category: 'Momos', image: IMG.paneerSteamMomos, veg: true, rating: 4.9, popular: true },
  { id: 47, name: 'Veg Fried Momos', description: '8 Piece — Crispy fried vegetable momos.', price: 160, category: 'Momos', image: IMG.vegFriedMomos, veg: true, rating: 0, popular: false },
  { id: 48, name: 'Veg Steam Momos', description: '8 Piece — Steamed vegetable dumplings.', price: 140, category: 'Momos', image: IMG.vegSteamMomos, veg: true, rating: 4.0, popular: false },

  // ── Snacks (3) ──
  { id: 49, name: 'Peri Peri Fries', description: 'Crispy golden fries tossed in a spicy peri peri sauce.', price: 140, category: 'Snacks', image: IMG.periPeriFries, veg: true, rating: 3.9, popular: true },
  { id: 50, name: 'Salted Fries', description: 'Crispy potato strips seasoned simply with salt.', price: 120, category: 'Snacks', image: IMG.saltedFries, veg: true, rating: 5.0, popular: false },
  { id: 51, name: 'Fries [Regular]', description: 'Thinly sliced potatoes and deep fried to crispy perfection.', price: 100, category: 'Snacks', image: IMG.regularFries, veg: true, rating: 5.0, popular: false },

  // ── Rumali Roti Paneer Shawarma (3) ──
  { id: 52, name: 'Rumali Brothers Special Paneer Shawarma', description: 'Succulent paneer infused with aromatic spices, wrapped in delicate Rumali Roti for a gourmet delight.', price: 169, category: 'Rumali Roti Paneer Shawarma', image: IMG.rumaliPaneerBrother, veg: true, rating: 0, popular: false },
  { id: 53, name: 'Rumali Hot And Spicy Paneer Shawarma', description: 'Fiery kick with zesty, marinated paneer wrapped in soft Rumali Roti for an intense flavor experience.', price: 169, category: 'Rumali Roti Paneer Shawarma', image: IMG.rumaliPaneerSpicy, veg: true, rating: 0, popular: false },
  { id: 54, name: 'Rumali Smooky Tandoori Paneer Shawarma', description: 'Smoky tandoori paneer wrapped in soft Rumali Roti, delivering a rich and savory taste with every bite.', price: 169, category: 'Rumali Roti Paneer Shawarma', image: IMG.rumaliPaneerTandoori, veg: true, rating: 0, popular: false },
]

export const CATEGORIES = [
  'All',
  'Shawarma Basic Choice',
  'Shawarma Special',
  'Paneer Shawarma',
  'Combos',
  'Special Veg Shawarma',
  'Special Rumali Roti Shawarma',
  'Momos',
  'Snacks',
  'Rumali Roti Paneer Shawarma',
]

export const OUTLETS = [
  {
    id: 1,
    name: 'Two Brothers Shawarma – Manish Nagar',
    rating: 4.0,
    type: 'Shawarma restaurant',
    address: 'Epicure Of opposite, The foody point, Manish Nagar, Vivekanand Nagar, Nagpur, Maharashtra 440037',
    hours: 'Opens 6:05 PM',
    phone: '7517736138',
    services: ['Dine-in', 'Delivery'],
    mapUrl: 'https://maps.app.goo.gl/ohV46cgbTDevTcns9',
    embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3721.5!2d79.0!3d21.1!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sManish+Nagar+Nagpur!5e0!3m2!1sen!2sin!4v1',
  },
  {
    id: 2,
    name: "Two Brother's Shawarma – IT Park (Opp. VNIT)",
    rating: 3.9,
    type: 'Shawarma restaurant',
    address: 'Opp. VNIT Main Gate, Gayatri Nagar, Jaitala, Nagpur, Maharashtra 440022',
    hours: 'Opens 11:30 AM',
    phone: '9819798753',
    services: ['Dine-in', 'Delivery'],
    mapUrl: 'https://maps.app.goo.gl/KWnAdYvcBgPgbYd56',
    embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3722.5!2d79.05!3d21.13!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sIT+Park+VNIT+Nagpur!5e0!3m2!1sen!2sin!4v1',
  },
  {
    id: 3,
    name: 'Two Brothers Shawarma – Ganesh Nagar',
    rating: 4.1,
    type: 'Fast food restaurant',
    address: 'Nandanvan Main Rd, beside Kotak Mahindra Bank, opposite HDFC Bank, Ganesh Nagar, Nagpur, Maharashtra 440024',
    hours: 'Opens 1 PM',
    phone: '7666050712',
    services: ['Dine-in', 'Drive-through', 'No-contact delivery'],
    mapUrl: 'https://maps.app.goo.gl/zHJ9f71Q37atqD3i6',
    embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3722.0!2d79.1!3d21.12!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sGanesh+Nagar+Nagpur!5e0!3m2!1sen!2sin!4v1',
  },
  {
    id: 4,
    name: 'Two Brothers Shawarma – Jafar Nagar',
    rating: 3.9,
    type: 'Fast food restaurant',
    address: 'Adarsh Colony, Jafar Nagar, New Mankapur, Nagpur, Maharashtra 440013',
    hours: 'Opens 2 PM',
    phone: '8668851656',
    services: ['Dine-in', 'Takeaway', 'Delivery'],
    mapUrl: 'https://maps.app.goo.gl/jcfm15uFnzeYs5BU6',
    embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3721.8!2d79.03!3d21.14!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sJafar+Nagar+Nagpur!5e0!3m2!1sen!2sin!4v1',
  },
]

export const GOOGLE_REVIEWS = [
  {
    id: 1,
    name: 'Khushi Choudhari',
    rating: 5,
    timeAgo: '8 months ago',
    text: "Hands down, it's the best shawarma in Nagpur. The vegetarian menu is also too delicious and mouth watering, every other variety has its own special flavour infused in it by the chef. It is entirely budget friendly, everything is under ₹200!",
    platform: 'Google',
  },
  {
    id: 2,
    name: 'Anshul Paunikar',
    rating: 5,
    timeAgo: '4 months ago',
    text: 'Awesome taste, must visit, fast service, best in the hood 😋',
    priceRange: '₹200–400',
    platform: 'Google',
  },
  {
    id: 3,
    name: 'Harshal Walke',
    rating: 5,
    timeAgo: '5 months ago',
    text: 'Best shawarma I ever tried in Nagpur!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 4,
    name: 'Khushboo Diwani',
    rating: 5,
    timeAgo: '8 months ago',
    text: 'They always serve fresh food, my favourite is crispy chicken shawarma 😋 Do visit it and have fun with your friends & family!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 5,
    name: 'Revati Gaikwad',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Taste is really good… I recommend zerk chicken shawarma!',
    platform: 'Google',
  },
  {
    id: 6,
    name: 'Manthan Gajbhiye',
    rating: 5,
    timeAgo: '5 months ago',
    text: 'Tried shawarma first time and Love it 😋😋',
    platform: 'Google',
  },
  {
    id: 7,
    name: 'Rohit Kirmire',
    rating: 5,
    timeAgo: '6 months ago',
    text: 'Best in business.. must try 🤤🤤',
    platform: 'Google',
  },
  {
    id: 8,
    name: 'Drishti Kande',
    rating: 5,
    timeAgo: '5 months ago',
    text: 'Best service, Best taste, Yummy!!',
    platform: 'Google',
  },
  {
    id: 9,
    name: 'Vipul Ganvir',
    rating: 5,
    timeAgo: '6 months ago',
    text: 'Must try Peri peri shawarma!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 10,
    name: 'Md Nasir',
    rating: 5,
    timeAgo: '9 months ago',
    text: 'Most Juicy Chicken shawarma in Nagpur!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 11,
    name: 'Shray Agarwal',
    rating: 4,
    timeAgo: '7 months ago',
    text: 'Best in taste with fresh chicken.',
    platform: 'Google',
  },
  {
    id: 12,
    name: 'Taresh Jain',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Best quality food and taste 🤤',
    platform: 'Google',
  },
  {
    id: 13,
    name: 'Sahil Shambharkar',
    rating: 5,
    timeAgo: '6 months ago',
    text: 'Always special shawarma — my go-to place!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 14,
    name: 'Harshal Jain',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Love the taste of paneer shawarma!',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 15,
    name: 'Pranit More',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Love the taste. Must try!',
    platform: 'Google',
  },
  {
    id: 16,
    name: 'KABEER MILIND PATIL',
    rating: 5,
    timeAgo: '5 months ago',
    text: 'Best shawarma in Nandanwan!',
    platform: 'Google',
  },
  {
    id: 17,
    name: 'Prakash Shende',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Very nice food and I like shawarma.',
    platform: 'Google',
  },
  {
    id: 18,
    name: 'Shreyas Lande',
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Awesome Taste fr.',
    platform: 'Google',
  },
  {
    id: 19,
    name: 'ASHOK BISHIKAR',
    rating: 5,
    timeAgo: '3 months ago',
    text: 'Good',
    priceRange: '₹1–200',
    platform: 'Google',
  },
  {
    id: 20,
    name: 'akshay deshmukh',
    rating: 5,
    timeAgo: '6 months ago',
    text: 'Nice shop good offers',
    platform: 'Google',
  },
]

export const GALLERY_IMAGES = [
  {
    id: 1,
    url: P(29850814),
    alt: 'Falafel Shawarma Wrap with Fries',
  },
  {
    id: 2,
    url: P(5779364),
    alt: 'Close-up Sliced Shawarma',
  },
  {
    id: 3,
    url: P(18177341),
    alt: 'Middle Eastern Wrap Platter',
  },
  {
    id: 4,
    url: P(29173105),
    alt: 'Herb-Crusted Paneer Tikka',
  },
  {
    id: 5,
    url: P(28445587),
    alt: 'Crispy Fried Momos',
  },
  {
    id: 6,
    url: P(115740),
    alt: 'Crispy French Fries with Dips',
  },
]

export const LINKS = {
  zomato: 'https://www.zomato.com/nagpur/two-brothers-shawarma-gayatri-nagar',
  swiggy: 'https://www.swiggy.com/city/nagpur/two-brothers-shawarma-gayatri-nagar-rest113722',
  whatsapp: 'https://wa.me/917517736138',
  phone: 'tel:+917517736138',
  maps: 'https://maps.app.goo.gl/ohV46cgbTDevTcns9',
  instagram: 'https://www.instagram.com/two_brothers_shawarma/?hl=en',
}
